In [1]:
from sklearn import preprocessing
import numpy as np


In [8]:
x=np.array([[1,2,3],
           [4,3,5],
           [5,7,8]])
x


array([[1, 2, 3],
       [4, 3, 5],
       [5, 7, 8]])

In [10]:
x_scaled= preprocessing.scale(x)
x_scaled

array([[-1.37281295, -0.9258201 , -1.13554995],
       [ 0.39223227, -0.46291005, -0.16222142],
       [ 0.98058068,  1.38873015,  1.29777137]])

In [13]:
x_scaled.std(axis=0)

array([1., 1., 1.])